/**
 * Deterministic export formatters for JDGC.
 * No server round-trip, no heavy deps — just pure string output.
 */
import type { LintResult } from '@/lib/lint/score';

export interface ExportDoc {
  jobTitle: string;
  body: string;
  lint?: LintResult | null;
  meta?: {
    generated?: string;
    model?: string;
    source?: string;
    [k: string]: string | undefined;
  };
}

export function toMarkdown(d: ExportDoc): string {
  const lines = [
    `# ${d.jobTitle || 'Untitled JD'}`,
    '',
  ];
  if (d.lint) {
    lines.push(
      `**Score:** ${d.lint.total}/100 · Grade ${d.lint.grade}  `,
      `**Structure:** ${d.lint.structure.score} · **Bias:** ${d.lint.bias.score} · **EUPTD:** ${d.lint.euptd.score}`,
      '',
    );
  }
  if (d.meta) {
    for (const [k, v] of Object.entries(d.meta)) {
      if (v) lines.push(`_${k}:_ ${v}  `);
    }
    lines.push('');
  }
  lines.push('---', '', d.body, '');
  if (d.lint && d.lint.findings.length) {
    lines.push('', '## Findings', '');
    for (const f of d.lint.findings) {
      lines.push(`- **[${f.severity.toUpperCase()}]** \`${f.ruleId}\` — ${f.message}${f.suggestion ? ` _→ ${f.suggestion}_` : ''}`);
    }
  }
  return lines.join('\n');
}

export function toJson(d: ExportDoc): string {
  return JSON.stringify(
    {
      jobTitle: d.jobTitle,
      body: d.body,
      lint: d.lint,
      meta: { ...d.meta, generated: d.meta?.generated || new Date().toISOString() },
    },
    null, 2,
  );
}

export function toCsv(d: ExportDoc): string {
  if (!d.lint) return 'ruleId,category,severity,message,suggestion\n';
  const header = 'ruleId,category,severity,message,suggestion';
  const rows = d.lint.findings.map(f =>
    [f.ruleId, f.category, f.severity, csvCell(f.message), csvCell(f.suggestion || '')].join(',')
  );
  return [header, ...rows].join('\n');
}

export function toPrintableHtml(d: ExportDoc): string {
  const esc = (s: string) => s.replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]!));
  const findings = d.lint?.findings
    .map(f => `<li><b>[${f.severity}]</b> <code>${f.ruleId}</code> — ${esc(f.message)}${f.suggestion ? ` <i>→ ${esc(f.suggestion)}</i>` : ''}</li>`)
    .join('\n') || '';
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${esc(d.jobTitle || 'JD')} · JDGC Report</title>
  <style>
    @page { size: A4; margin: 18mm 16mm; }
    body { font: 12px/1.6 "DM Sans", -apple-system, sans-serif; color: #1A1A1A; background: #F6F4EF; }
    .sheet { max-width: 780px; margin: 0 auto; padding: 32px; background: white; }
    h1 { font: 700 24px/1.2 "Playfair Display", serif; margin: 0 0 4px; }
    .meta { color: #666; font-size: 11px; margin-bottom: 20px; }
    .score { display: flex; gap: 12px; margin: 16px 0 24px; padding: 12px 16px; background: #FAF6EE; border-left: 3px solid #8A7560; }
    .score .kpi { font-size: 11px; text-transform: uppercase; letter-spacing: .06em; color: #666; }
    .score .val { font: 700 22px/1 "Playfair Display", serif; }
    .body { white-space: pre-wrap; font-size: 13px; line-height: 1.7; margin-bottom: 24px; }
    h2 { font: 700 16px/1.2 "Playfair Display", serif; border-bottom: 1px solid #eee; padding-bottom: 4px; }
    ul { padding-left: 18px; }
    li { margin: 4px 0; font-size: 11px; }
    code { font: 10px "Menlo", monospace; background: #F6F4EF; padding: 1px 4px; border-radius: 3px; }
    .footer { margin-top: 32px; border-top: 1px solid #eee; padding-top: 12px; font-size: 10px; color: #888; }
    @media print { body { background: white; } .sheet { padding: 0; } }
  </style>
</head>
<body>
  <div class="sheet">
    <h1>${esc(d.jobTitle || 'Untitled JD')}</h1>
    <div class="meta">
      ${[d.meta?.source, d.meta?.model, d.meta?.generated || new Date().toLocaleString()].filter((x): x is string => !!x).map(esc).join(' · ')}
    </div>
    ${d.lint ? `
    <div class="score">
      <div><div class="kpi">Total</div><div class="val">${d.lint.total}</div></div>
      <div><div class="kpi">Grade</div><div class="val">${d.lint.grade}</div></div>
      <div><div class="kpi">Structure</div><div class="val">${d.lint.structure.score}</div></div>
      <div><div class="kpi">Bias</div><div class="val">${d.lint.bias.score}</div></div>
      <div><div class="kpi">EUPTD</div><div class="val">${d.lint.euptd.score}</div></div>
    </div>` : ''}
    <div class="body">${esc(d.body)}</div>
    ${d.lint && d.lint.findings.length ? `<h2>Findings (${d.lint.findings.length})</h2><ul>${findings}</ul>` : ''}
    <div class="footer">Generated by JD Suite · privacy-first, client-side · Built by <a href="https://www.linkedin.com/in/tomaszrey" target="_blank" rel="noopener noreferrer">Tomasz Rey</a>.</div>
  </div>
  <script>window.print && setTimeout(() => window.print(), 300);</script>
</body>
</html>`;
}

function csvCell(s: string) {
  if (!s) return '';
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function downloadText(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export function openHtmlInNewWindow(html: string) {
  const w = window.open('', '_blank');
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
}
